# Generated by Django 4.0.4 on 2022-04-13 04:03

import cats.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to=cats.models.cat_image_path)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
