# Generated by Django 4.0.4 on 2022-05-05 03:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Dnd_Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('elemental', models.BooleanField(default=False)),
                ('conditional', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('level', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)])),
                ('casting_time', models.CharField(choices=[('action', 'Action'), ('bonus', 'Bonus Action'), ('reaction', 'Reaction'), ('other', 'other')], default='action', max_length=8)),
                ('range', models.IntegerField()),
                ('components', models.CharField(max_length=16)),
                ('duration', models.IntegerField()),
                ('school', models.CharField(choices=[('abjuration', 'Abjuration'), ('conjuration', 'Conjuration'), ('divination', 'Divination'), ('enchantment', 'Enchantment'), ('evocation', 'Evocation'), ('illusion', 'Illusion'), ('necromancy', 'Necromancy'), ('transmutation', 'Transmutation')], max_length=16)),
                ('attack_save', models.CharField(choices=[('str', 'STR'), ('dex', 'DEX'), ('con', 'CON'), ('int', 'INT'), ('wis', 'WIS'), ('cha', 'CHA'), ('none', 'None')], max_length=4)),
                ('description', models.TextField()),
                ('classes', models.ManyToManyField(to='dnd.dnd_class')),
                ('conditions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd.condition')),
                ('effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd.effect')),
                ('elements', models.ManyToManyField(to='dnd.element')),
            ],
        ),
    ]
