# Generated by Django 3.2.9 on 2022-05-09 20:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0002_condition_description_alter_spell_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spell_Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.RemoveField(
            model_name='effect',
            name='conditional',
        ),
        migrations.RemoveField(
            model_name='effect',
            name='elemental',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='effect',
        ),
        migrations.AddField(
            model_name='spell',
            name='area',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='spell',
            name='area_shape',
            field=models.CharField(blank=True, choices=[('cone', 'Cone'), ('sphere', 'Sphere'), ('square', 'Square'), ('line', 'Line'), ('feet2', 'Feet²'), ('flat_square', 'Flat Square'), ('cylinder', 'cylinder')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='spell',
            name='duration_num',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='spell',
            name='duration_str',
            field=models.CharField(choices=[('instantaneous', 'Instantaneous'), ('round', 'Round'), ('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day'), ('special', 'Special')], default='round', max_length=16),
        ),
        migrations.AddField(
            model_name='spell',
            name='effects',
            field=models.ManyToManyField(to='dnd.Effect'),
        ),
        migrations.AddField(
            model_name='spell',
            name='is_concentration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spell',
            name='is_ritual',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='effect',
            name='name',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='spell',
            name='attack_save',
            field=models.CharField(blank=True, choices=[('str', 'STR'), ('dex', 'DEX'), ('con', 'CON'), ('int', 'INT'), ('wis', 'WIS'), ('cha', 'CHA'), ('melee', 'Melee'), ('ranged', 'Ranged')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='casting_time',
            field=models.CharField(choices=[('action', 'Action'), ('bonus', 'Bonus Action'), ('reaction', 'Reaction'), ('minute', '1 Minute'), ('10 minutes', '10 Minutes'), ('hour', '1 Hour'), ('8 hours', '8 Hours'), ('12 hours', '12 Hours'), ('24 hours', '24 Hours'), ('other', 'other')], default='action', max_length=16),
        ),
        migrations.RemoveField(
            model_name='spell',
            name='components',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='conditions',
        ),
        migrations.AddField(
            model_name='spell',
            name='conditions',
            field=models.ManyToManyField(blank=True, to='dnd.Condition'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='elements',
            field=models.ManyToManyField(blank=True, to='dnd.Element'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='level',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='spell',
            name='range',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='spell',
            name='components',
            field=models.ManyToManyField(to='dnd.Spell_Component'),
        ),
    ]
