# Generated by Django 4.0.4 on 2022-07-20 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0005_alter_spell_components_alter_spell_elements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='casting_time',
            field=models.IntegerField(default=0),
        ),
    ]
